version: '3'

services:
  iot-dht22:
    image: iot-dht22:latest
    container_name: iot-dht22
    restart: unless-stopped
    privileged: true
    depends_on:
      - mqtt-to-influxdb

  mqtt-to-influxdb:
    image: mqtt-to-influxdb:latest
    container_name: mqtt-to-influxdb
    restart: unless-stopped
    depends_on:
      - mosquitto
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    restart: unless-stopped
    ports:
     - "9001:9001"
     - "1883:1883"
    volumes:
     - ./volumes/mosquitto:/mosquitto/config

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
     - "8083:8083"
     - "8086:8086"
    volumes:
     - ./volumes/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    env_file:
     - './env/grafana'
    restart: unless-stopped
    ports:
     - "3000:3000"
    volumes:
      - ./volumes/grafana/db:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
      - ./volumes/grafana/conf:/etc/grafana
