version: '3'

services:
  iot-python:
    image: iot-python:latest
    container_name: iot-python
    restart: always
    privileged: true
    depends_on:
      - mqtt-python

  mqtt-python:
    image: mqtt-python:latest
    container_name: mqtt-python
    restart: always
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    depends_on:
      - influxdb
    ports:
     - "9001:9001"
     - "1883:1883"
    volumes:
     - ./volumes/mosquitto:/mosquitto/config

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
     - "8083:8083"
     - "8086:8086"
    volumes:
     - ~/docker/influxdb/data:/data

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - ./volumes/grafana/db:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
      - ./volumes/grafana/conf:/etc/grafana
#    networks:
#      - host

#networks:
#  host:
#    external: true
