version: '3'

services:
  iot-sct013:
    image: iot-sct013:latest
    build:
      dockerfile: Dockerfile.sct013
      context: .
    container_name: iot-sct013
    restart: unless-stopped
    privileged: true
